SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'o%' OR CITY LIKE 'u%';
-- SELECT CITY FROM STATION WHERE CITY LIKE 'e%';
-- SELECT CITY FROM STATION WHERE CITY LIKE 'i%';
-- SELECT CITY FROM STATION WHERE CITY LIKE 'o%';
-- SELECT CITY FROM STATION WHERE CITY LIKE 'u%';